services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    image: ${PROJECT_NAME}-node
    container_name: ${PROJECT_NAME}-node-${NODE_ENV}
    command: "npm run start"
    ports:
      - ${PORT}:${PORT}
