name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        
      - name: Set environment variables
        run: |
          echo "TZ=IST" >> $GITHUB_ENV
          echo "PORT=3333" >> $GITHUB_ENV
          echo "HOST=0.0.0.0" >> $GITHUB_ENV
          echo "LOG_LEVEL=trace" >> $GITHUB_ENV
          echo "APP_KEY=test1234" >> $GITHUB_ENV
          echo "NODE_ENV=test" >> $GITHUB_ENV
          echo "DB_CONNECTION=pg" >> $GITHUB_ENV
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> $GITHUB_ENV
          echo "CLIENT_API_KEY=${{ secrets.CLIENT_API_KEY }}" >> $GITHUB_ENV
          echo "HEALTH_CHECK_API_KEY=healthTest1234" >> $GITHUB_ENV
          echo "LOCK_STORE=database" >> $GITHUB_ENV

        
      - name: Run tests
        run: npm test
